### ISSUE TITLE
First data collection

### ISSUE THREAD

**Issue by bruno-f-cruz** [AllenNeuralDynamics/Aind.Behavior.VideoEncodingBenchmarks#1]
Opening this meta-issue to keep questions regarding the data collection in one place.

Following what we agreed from the meetings discussing the video standards, these are the metrics we will be looking at:

- Compression ratio (Given by bytes_raw (can be easily calculated by W * H * fps * seconds) / bytes_compressed_video)

- Performance
  - Logging the output of the ffmpeg process (check if it is running real-time)
  - Keep an eye on the memory accumulation

- Drop frames (qc is performed online + can be reproduced using the metadata post hoc)

- Quality index (@galenlynch did you have some sort of algorithm to look at this?)

**Comment by bruno-f-cruz** [comment]
I made an update of some core dependencies of the repository to make maintenance a bit easier in the future. All data will be fully compatible with the previous version, HOWEVER if you have cloned the repository before, make sure to delete all temporary folders inside the `./bonsai` directory and run `setup.cmd` again to bootstrap the new bonsai version. Sorry for the potential trouble.

You can also not pull from main and keep on acquiring with the current commit sha, no worries!

**Comment by galenlynch** [comment]
I ran the script here but did not see the output of ffmpeg, or any other output while the benchmark was running. Perhaps we can touch base to evaluate whether there were any dropped frames. the CPU use for two 500 FPS cameras was 33%.

**Comment by bruno-f-cruz** [comment]
Closing this for now. If the team wants to plan something systematic, the library is in a good place to do so right now, but we can start a new issue after an initial discussion.
