### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by galenlynch** [AllenNeuralDynamics/Aind.Behavior.VideoEncodingBenchmarks#16]
After building the environment on v0.2.1 and running the launcher.cmd script I see the following missing deps which cause errors:
`aind-watchdog-service`, `aind-data-schema`. I got the same error on main.

**Comment by bruno-f-cruz** [comment]
If you are looking to use the launcher, you will unfortunately need to install the optional dependencies from the pyproject.toml

https://github.com/AllenNeuralDynamics/Aind.Behavior.VideoEncodingBenchmarks/blob/a8a38a2cfbe73cff169f36eb4bfdba8abae71c97/pyproject.toml#L22-L24

The import error should actually provide some information about this, no?

**Comment by bruno-f-cruz** [comment]
I cleaned up the readme instructions in 5d4e8803c63ec7eb2f3df57efdf8867846e8e1d3. I will close this for now, but feel free to re-open/make a PR for further clarification.
