### ISSUE TITLE
 Some suggested edits to instructions

### ISSUE THREAD

**Issue by galenlynch** [AllenNeuralDynamics/Aind.Behavior.VideoEncodingBenchmarks#4]
I had some problems following the instructions. It would have been clearer to me if the instructions:

1. Specified that most scripts expect to be executed in the base directory of the repo, and not in the scripts directory itself.
2. Explicitly instructed the user to activate the environment created by `deploy.cmd` for any scripts, or specified an execution environment (vscode may already do this)
3. Added instructions to copy `examples/examples.py` outside of the repo and modify it (this avoids a dirty repo which blocks the CLABE script)
4. Included a step to execute the json generating script, as I was not clear if the metadata were the script itself (some projects use python files as config files) or products of the script
5. Specified what to do with the saved data, where to put it, or how to validate

**Comment by bruno-f-cruz** [comment]
Check #8 for a potential fix.

Regarding 
> 5. Specified what to do with the saved data, where to put it, or how to validate

For the saved data I think we can go with scratch for now and dump it under `\\allen\aind\scratch\aind-behavior-videoencodingbenchmarks`


As for the validation, I think we should discuss this during the software meeting. My two cents: once we have collected data from every single person assigned in #1  and make sure that compression can operate online, we can decide what validation to run. I would like to follow some of the points in #1
